title: "Mayur Khadde"
author: "Mayur Khadde"
description: "Normal Protfolio about myself, projects and few blogs"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

markdown: kramdown
kramdown:
  math_engine: katex

# Layout
sidebar: true                # show a sidebar instead of the usual header
show_excerpts: true          # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true             # always keep the site title visible

# Styling
dark_header: true            # always keep the header dark
minimal: false               # use simpler style


header_pages:
  - about.md
  - index.html
  - software.md

# Menu
navigation:
  - {file: "about.md", icon: address-card}
  - {file: "index.html", icon: home}
  - {file: "software.md", icon: cube}

external:                    # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mayurkhadde49@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/bashlogs"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/mayurkhadde"}
  - {title: RSS, icon: rss, url: "/feed.xml"}

comments:
  disqus: true
  disqus_shortname: Mayur        # see https://disqus.com/


plugins: 
  - jekyll-feed
  

